/**
 * Навигация
 * Основные экраны
 */

export const NAVIGATION_AUTH = 'NAVIGATION/AUTH';
export const NAVIGATION_APP = 'NAVIGATION/APP';

/**
 * User stack navigation
 */
export const USER_STACK_NAVIGATION = {
  STACK: 'USER_STACK_NAVIGATION_STACK',
  LIST: 'USER_STACK_NAVIGATION_TASK_LIST',
  DETAIL: 'USER_STACK_NAVIGATION_TASK_DETAIL',
  CREATE_TASK: 'USER_STACK_NAVIGATION_TASK_CREATE',
};
/**
 * Admin stack navigation
 */
export const ADMIN_STACK_NAVIGATION = {
  STACK: 'ADMIN_STACK_NAVIGATION_STACK',
  LIST: 'ADMIN_STACK_NAVIGATION_USER_LIST',
  DETAIL: 'ADMIN_STACK_NAVIGATION_USER_DETAIL',
  CREATE: 'ADMIN_STACK_NAVIGATION_USER_CREATE',
};

/**
 * Manager stack navigation
 */
export const MANAGER_STACK_NAVIGATION = {
  STACK: 'MANAGER_STACK_NAVIGATION_STACK',
  USERS: 'MANAGER_STACK_NAVIGATION_USERS',
  LIST: 'MANAGER_STACK_NAVIGATION_TASK_LIST',
  DETAIL: 'MANAGER_STACK_NAVIGATION_TASK_DETAIL',
  CREATE: 'MANAGER_STACK_NAVIGATION_TASK_CREATE',
};
